# Generated by Django 6.1.1 on 2026-09-29 09:56

import accountings.scripts.unique
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0002_product_stock'),
        ('information', '0004_alter_expensemodel_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter the available quantity of the product'),
        ),
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_sku', models.CharField(default=accountings.scripts.unique.generate_sales_sku, editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sales_types', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=10)),
                ('location', models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside')], max_length=10)),
                ('quantity', models.IntegerField(default=0, help_text='Enter the quantity of the product sold')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the price of the product', max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=13.0, editable=False, max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accountings.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accountings.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='information.suppliermodel')),
            ],
        ),
    ]
