# Generated by Django 6.1.1 on 2026-09-29 10:05

import accountings.scripts.unique
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0003_product_quantity_salesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount in Rs.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate in %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price at the time of sale', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='sales_sku',
            field=models.CharField(default=accountings.scripts.unique.generate_sales_sku, editable=False, help_text='Stock Keeping Unit — auto-generated.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount in Rs. (subtotal − discount + VAT)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesmodel',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='VAT amount in Rs. (computed from VAT % at save time)', max_digits=10),
        ),
    ]
