# Generated by Django 6.1 on 2026-09-03 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_office_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Limited Liability Company (LLC)', 'Limited Liability Company (LLC)'), ('Nonprofit Organization', 'Nonprofit Organization'), ('Cooperative', 'Cooperative'), ('Joint Venture', 'Joint Venture'), ('Franchise', 'Franchise'), ('Government-Owned Corporation', 'Government-Owned Corporation'), ('Multinational Corporation (MNC)', 'Multinational Corporation (MNC)'), ('Holding Company', 'Holding Company'), ('Subsidiary', 'Subsidiary'), ('Conglomerate', 'Conglomerate'), ('Professional Corporation (PC)', 'Professional Corporation (PC)'), ('Benefit Corporation (B Corp)', 'Benefit Corporation (B Corp)'), ('Public-Private Partnership (PPP)', 'Public-Private Partnership (PPP)'), ('Limited Liability Partnership (LLP)', 'Limited Liability Partnership (LLP)'), ('S-Corporation', 'S-Corporation'), ('C-Corporation', 'C-Corporation')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.AlterField(
            model_name='userloginprefernce',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='accounts.companyinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
