# Generated by Django 6.1.1 on 2026-09-23 19:01

import information.scripts.suppliercode
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountings', '0002_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('adress', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('provience', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('History', models.TextField(blank=True, null=True)),
                ('code', models.CharField(default=information.scripts.suppliercode.generate_supplier_code, editable=False, max_length=50, unique=True)),
                ('supplier_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], max_length=100)),
                ('supplier_type_company', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], max_length=100)),
                ('supplier_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100)),
                ('supplier_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter the supplier rating (0.00 to 5.00)', max_digits=3)),
                ('supplier_company', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('government', 'Government'), ('non-profit', 'Non-Profit'), ('individual', 'Individual')], max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products_supplied', models.ManyToManyField(related_name='suppliers', to='accountings.product')),
            ],
        ),
    ]
