# Generated by Django 6.1.1 on 2026-09-24 18:01

import information.scripts.suppliercode
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(default=information.scripts.suppliercode.reference_number_code, editable=False, max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), editable=False, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expense_type', models.CharField(choices=[('office', 'Office'), ('personal', 'Personal')], default='office', max_length=20)),
                ('transaction_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment')], default='cash', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expense_images/')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='expense_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
