# Generated by Django 6.1.1 on 2026-09-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_expensemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_mrr_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_market_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expansion_customers_target', models.PositiveIntegerField()),
                ('penetration_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
