# Generated by Django 6.1.1 on 2026-09-24 20:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_expansiontarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='tax_rate',
            field=models.DecimalField(decimal_places=0, default=Decimal('13.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
